### ISSUE TITLE
Error in useParagonGlobal with Typescript

### ISSUE THREAD

**Issue by prateekjain98** [useparagon/paragon-connect-nextjs-example#1]
I have the project built in Typescript and when I use the existing code of useParagonGlobal hook, it gives error for window.paragon and paragon.
![paragonError](https://user-images.githubusercontent.com/49878260/228860700-08913d8f-7caf-41e4-8fd9-83b258dc458b.png)

**Comment by nrayamajhee** [comment]
You might want to add this to tell TS that paragon object exists in global window:
```
declare global {
  interface Window {
    paragon: any
  }
}
```

**Comment by nrayamajhee** [comment]
Actually, I found the type definitions here:
<https://github.com/useparagon/paragon-integrations-catalog-tutorial/blob/master/src/paragon.d.ts>

**Comment by ethanlee16** [comment]
Good find @nrayamajhee, and thanks for flagging @prateekjain98 - I just updated this repository to use our new npm package, which ships with our official TS types. 

If you're already using the `<script>` tag or importing our types via a global types file, see our migration instructions in the docs: https://docs.useparagon.com/getting-started/installing-the-connect-sdk

Thanks!
